# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: natours
spec:
  replicas: 3
  selector:
    matchLabels:
      app: natours
  template:
    metadata:
      labels:
        app: natours
    spec:
      containers:
        - name: natours
          image: 686317197365.dkr.ecr.us-east-1.amazonaws.com/natours:latest
          ports:
            - containerPort: 8080