# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: natours-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Specify the Ingress Controller class
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: natours  
                port:
                  number: 80
