# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: natours
spec:
  selector:
    app: natours
  ports:
    - protocol: TCP
      port: 80  # Expose Node.js app on port 80
      targetPort: 3000  # Point to the container port of your Node.js app
  type: ClusterIP  # Expose the Service internally within the cluster
