# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: elb
spec:
  type: LoadBalancer
  ports:
  - name: http-port
    port: 80
    targetPort: 8080
  - name: https-port
    port: 443
    targetPort: 8080
  selector:
    app: natours
